import React from 'react'
import { SafeAreaView, ScrollView, Text } from 'react-native'
import DiaryCell from '../../../Components/DiaryCell';

const demoDiaries = [

  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },
  { date: "1/2/2023", title: "title", content: "content" },

];

const DiaryHistory = () => {
  return (
    <SafeAreaView className='flex-1 items-center'>
      <ScrollView>
        {demoDiaries.map((d, i) =>
          <DiaryCell id={1} key={i} date={d.date} title={d.title} content={d.content} />
        )}
      </ScrollView>

    </SafeAreaView>
  )
}
export default DiaryHistory
